const PLAYER_STATUS_OK = 'a';
const PLAYER_STATUS_MINOR = 'd';
const PLAYER_STATUS_SEVERE = 'i';
const PLAYER_STATUS_SUSPENDED = 's';
const PLAYER_STATUS_TRANSFER = 'u';
const PLAYER_MINIMUM_MINUTES = 90;

module.exports = {
    PLAYER_STATUS_OK,
    PLAYER_STATUS_MINOR,
    PLAYER_STATUS_SEVERE,
    PLAYER_STATUS_SUSPENDED,
    PLAYER_STATUS_TRANSFER,
    PLAYER_MINIMUM_MINUTES,
}